<form id="<?php echo $this->element->getId();?>" class="contactForm" method="<?php echo $this->element->getMethod();?>" action="<?php echo $this->element->getAction();?>">
<pre>
<div><b>Name:</b><?php echo $this->element->name;?></div>
<div><b>Email:</b><?php echo $this->element->email;?></div>
<div><b>Message:</b><?php echo $this->element->message; ?></div>
<?php echo $this->element->submit;?>
</pre>
</form>