<!DOCTYPE html>
<html lang="en">
    <head>
<!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->          <title><?= (!is_null($this->pageTitle)) ? $this->pageTitle : "AllStuffComputers - PC Reviews, Best Selling PC Systems"; ?></title>
          <meta charset="utf-8" />
          <meta property="og:title" content="Computers"/>
          <meta property="og:type" content="computers"/>
          <meta property="og:url" content="http://localhost/"/>
          <meta property="og:image" content=""/>
          <meta property="og:site_name" content="AllStuffComputers"/>
          <meta property="fb:admins" content="156566244489399"/>
          <meta property="og:description"
                content="Shop computers and hardware tablets hard drives laptops desktops printers scanners routers
                buying guides"/>
          <link rel="stylesheet" href="/styles.css" type="text/css" />
          <script type="text/javascript" src="/js/jquery-1.8.2.min.js"></script>
          <script type="text/javascript" src="/js/utilities.js"></script>
          <script type="text/javascript" src="/js/errorMessages.js"></script>
          <script type="text/javascript" src="/js/global_effects.js"></script>
          <script type="text/javascript" src="/js/form_validations.js"></script>
          <script type="text/javascript" src="/js/allstuffcomputers.js"></script>
<!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->          <title><?= (!is_null($this->pageTitle)) ? $this->pageTitle : "AllStuffComputers - PC Reviews, Best Selling PC Systems"; ?></title>
    </head>
    <body>
        <div id="container">
            <div id="header">
                <div class="logo">
                </div>
                <div class="banner">
                </div>
                <div class="navLinks">
                    <ul>
                        <li><a href="/">Home</a></li> 
                        <li><a href="/products/laptops">Laptops</a>
                            <ul>
                                <li><a href="/products/laptops/brand/acer">Acer</a></li>
                                <li><a href="/products/laptops/brand/alienware">Alienware</a></li>
                                <li><a href="/products/laptops/brand/apple">Apple</a></li>
                                <li><a href="/products/laptops/brand/asus">Asus</a></li>
                                <li><a href="/products/laptops/brand/dell">Dell</a></li>
                                <li><a href="/products/laptops/brand/gateway">Gateway</a></li>
                                <li><a href="/products/laptops/brand/hp">HP</a></li>
                                <li><a href="/products/laptops/brand/lenovo">Lenovo</a></li>                                
                                <li><a href="/products/laptops/brand/sony">Sony</a></li>
                                <li><a href="/products/laptops/brand/toshiba">Toshiba</a></li>
                            </ul>
                        </li>
                        <li><a href="/products/desktops">Desktops</a>
                            <ul>
                                <li><a href="/products/desktops/brand/acer">Acer</a></li>
                                <li><a href="/products/desktops/brand/alienware">Alienware</a></li>
                                <li><a href="/products/desktops/brand/apple">Apple</a></li>
                                <li><a href="/products/desktops/brand/asus">Asus</a></li>
                                <li><a href="/products/desktops/brand/dell">Dell</a></li>
                                <li><a href="/products/desktops/brand/gateway">Gateway</a></li>
                                <li><a href="/products/desktops/brand/hp">HP</a></li>
                                <li><a href="/products/desktops/brand/lenovo">Lenovo</a></li>                                
                                <li><a href="/products/desktops/brand/sony">Sony</a></li>
                                <li><a href="/products/desktops/brand/toshiba">Toshiba</a></li>  
                            </ul>
                        </li>
                        <li><a href="/products/tablets">Tablets</a>
                            <ul>
                                <li><a href="/products/tablets/brand/acer">Acer</a></li>
                                <li><a href="/products/tablets/brand/amazon">Amazon Kindle</a></li>
                                <li><a href="/products/tablets/brand/apple">Apple</a></li>
                                <li><a href="/products/tablets/brand/archos">Archos</a></li>
                                <li><a href="/products/tablets/brand/asus">Asus</a></li>
                                <li><a href="/products/tablets/brand/atc">Atc</a></li>
                                <li><a href="/products/tablets/brand/blackberry">Blackberry</a></li>
                                <li><a href="/products/tablets/brand/dell">Dell</a></li>
                                <li><a href="/products/tablets/brand/google">Google Nexus</a></li>
                                <li><a href="/products/tablets/brand/hp">HP</a></li>
                                <li><a href="/products/tablets/brand/htc">HTC</a></li>
                                <li><a href="/products/tablets/brand/oem">OEM SYSTEMS</a></li>
                                <li><a href="/products/tablets/brand/motorola">Motorola</a></li>
                                <li><a href="/products/tablets/brand/samsung">Samsung</a></li>                                
                                <li><a href="/products/tablets/brand/sony">Sony</a></li>
                                <li><a href="/products/tablets/brand/toshiba">Toshiba</a></li>
                                <li><a href="/products/tablets/brand/viewsonic">Viewsonic</a></li>  
                            </ul>
                        </li>
                        <li><a href="/products/hdd">External Hard Drives</a>
                            <ul>
                                <li><a href="/products/hdd/brand/buffalo">Buffalo</a></li>
                                <li><a href="/products/hdd/brand/hp">HP</a></li>
                                <li><a href="/products/hdd/brand/iomega">Iomega</a></li>
                                <li><a href="/products/hdd/brand/kingston">Kingston</a></li>
                                <li><a href="/products/hdd/brand/lacie">LaCie</a></li>
                                <li><a href="/products/hdd/brand/seagate">Seagate</a></li>
                                <li><a href="/products/hdd/brand/synology">Synology</a></li>
                                <li><a href="/products/hdd/brand/toshiba">Toshiba</a></li>
                                <li><a href="/products/hdd/brand/transcend">Transcend</a></li>
                                <li><a href="/products/hdd/brand/verbatim">Verbatim</a></li>
                                <li><a href="/products/hdd/brand/western digital">Western Digital</a></li>
                            </ul>
                        </li>
                        <li><a href="/products/printers">Printers/Scanners</a>
                            <ul>
                                <li><a href="/products/printers/brand/brother">Brother</a></li>
                                <li><a href="/products/printers/brand/canon">Canon</a></li>
                                <li><a href="/products/printers/brand/epson">Epson</a></li>                              
                                <li><a href="/products/printers/brand/hp">HP</a></li>
                                <li><a href="/products/printers/brand/kodak">Kodak</a></li>
                                <li><a href="/products/printers/brand/lexmark">Lexmark</a></li>
                                <li><a href="/products/printers/brand/okidata">Oki Data</a></li>
                                <li><a href="/products/printers/brand/panasonic">Panasonic</a></li>
                                <li><a href="/products/printers/brand/ricoh">Ricoh</a></li>
                                <li><a href="/products/printers/brand/samsung">Samsung</a></li>
                            </ul>
                        </li>
                        <li><a href="/products/monitors">Monitors</a>
                            <ul>
                                <li><a href="/products/monitors/brand/acer">Acer</a></li>
                                <li><a href="/products/monitors/brand/apple">Apple</a></li> 
                                <li><a href="/products/monitors/brand/asus">Asus</a></li>
                                <li><a href="/products/monitors/brand/dell">Dell</a></li>
                                <li><a href="/products/monitors/brand/gateway">Gateway</a></li>
                                <li><a href="/products/monitors/brand/hp">HP</a></li>                  
                                <li><a href="/products/monitors/brand/lenovo">Lenovo</a></li>
                                <li><a href="/products/monitors/brand/panasonic">Panasonic</a></li>
                                <li><a href="/products/monitors/brand/samsung">Samsung</a></li>
                                <li><a href="/products/monitors/brand/sony">Sony</a></li>
                                <li><a href="/products/monitors/brand/toshiba">Toshiba</a></li>
                                <li><a href="/products/monitors/brand/viewsonic">Viewsonic</a></li>
                            </ul>
                        </li>
                        <li><a href="/products/routers">Routers</a>
                            <ul>
                                <li><a href="/products/routers/brand/belkin">Belkin</a></li>
                                <li><a href="/products/routers/brand/buffalo">Buffalo</a></li>
                                <li><a href="/products/routers/brand/cisco">Cisco LinkSys</a></li>
                                <li><a href="/products/routers/brand/dlink">D-Link</a></li>
                                <li><a href="/products/routers/brand/lgericsson">LG-Ericsson</a></li>
                                <li><a href="/products/routers/brand/motorola">Motorola</a></li>
                                <li><a href="/products/routers/brand/netgear">Netgear</a></li> 
                                <li><a href="/products/routers/brand/tplink">TP-Link</a></li>
                                <li><a href="/products/routers/brand/trendnet">TrendNet</a></li>   
                                <li><a href="/products/routers/brand/western digital">Western Digital</a></li>
                            </ul>
                        </li>
                        <li><a href="/info/contact">Contact</a></li>          
                    </ul>
                </div>
            </div>
             <div id="left_nav">
                 <h3>Site Info</h3>
                 <ul>
                     <li><a href="/">Homepage</a></li>
                     <li><a href="/info/about">About</a></li>
                     <li><a href="/info/contact">Contact</a></li>
                 </ul>
                 
                 <h3>Guides</h3>
                 <ul>
                    <li><a href="/guides/laptops">Laptop Buying Guide</a></li>
                     <li><a href="/">Desktop Buying Guide</a></li>
                     <li><a href="/">Tablet Buying Guide</a></li>
                     <li><a href="/">Hard Drive Buying Guide</a></li>
                     <li><a href="/">Router Buying Guide</a></li>
                 </ul>
                 
                 <h3>Top Computers</h3>
                 <ul>
                        <li><a href="/products/laptops">Laptop Reviews</a>
                        <li><a href="/products/desktops">Desktop Reviews</a>
                        <li><a href="/products/tablets">Tablet Reviews</a>
                        <li><a href="/products/hdd">Hard Drive Reviews</a>
                        <li><a href="/products/printers">Printer/Scanner Reviews</a>
                        <li><a href="/products/monitors">Monitor Reviews</a>
                        <li><a href="/products/routers">Router Reviews</a>
                 </ul>
            </div>
            
            <div id="content">
                <?php if(isset($this->messages[0])): ?>
                    <div class="flashDiv">
                        <?php echo $this->messages[0]; ?>
                    </div>
                <?php endif; ?>
                
                <?php echo $this->layout()->content; ?>
            </div>
            
            <div id="footer">
                <br/>
                Copyright &copy 2012 Vishaan Tiwarie
                <br/>
                <br/>
                AllStuffComputers.com 
            </div>
        </div>
   
    </body>    
</html>