<!DOCTYPE html">
<html lang="en">
    <head>
          <title><?= (!is_null($this->pageTitle)) ? $this->pageTitle : "AllStuffComputers - PC Reviews, Best Selling PC Systems"; ?></title>
          <meta charset="utf-8" />
          <meta property="og:title" content="Computers"/>
          <meta property="og:type" content="computers"/>
          <meta property="og:url" content="http://localhost/"/>
          <meta property="og:image" content=""/>
          <meta property="og:site_name" content="AllStuffComputers"/>
          <meta property="fb:admins" content="156566244489399"/>
          <meta property="og:description"
                content="Shop computers and hardware tablets hard drives laptops desktops printers scanners routers
                buying guides"/>
          <link rel="stylesheet" href="../styles.css" type="text/css" />
          <script type="text/javascript" src="../js/jquery-1.8.2.min.js"></script>
          <script type="text/javascript" src="../js/utilities.js"></script>
          <script type="text/javascript" src="../js/global_effects.js"></script>
          <script type="text/javascript" src="../js/allstuffcomputers.js"></script>
    </head>
    
    <body>
        <div id="container">
            <div id="header">
                <div class="logo">
                </div>
                <div class="banner">
                </div>
                <div class="navLinks">
                    <ul>
                        <li><a href="../">Home</a></li>
                        <li><a href="../laptops">Laptops</a>
                            <ul>
                                <li><a href="../laptops/acer">Acer</a></li>
                                <li><a href="../laptops/alienware">Alienware</a></li>
                                <li><a href="../laptops/apple">Apple</a></li>
                                <li><a href="../laptops/asus">Asus</a></li>
                                <li><a href="../laptops/dell">Dell</a></li>
                                <li><a href="../laptops/gateway">Gateway</a></li>
                                <li><a href="../laptops/hp">HP</a></li>
                                <li><a href="../laptops/lenovo">Lenovo</a></li>                                
                                <li><a href="../laptops/sony">Sony</a></li>
                                <li><a href="../laptops/toshiba">Toshiba</a></li>
                            </ul>
                        </li>
                        <li><a href="../desktops">Desktops</a>
                            <ul>
                                <li><a href="../desktops/acer">Acer</a></li>
                                <li><a href="../desktops/alienware">Alienware</a></li>
                                <li><a href="../desktops/apple">Apple</a></li>
                                <li><a href="../desktops/asus">Asus</a></li>
                                <li><a href="../desktops/dell">Dell</a></li>
                                <li><a href="../desktops/gateway">Gateway</a></li>
                                <li><a href="../desktops/hp">HP</a></li>
                                <li><a href="../desktops/lenovo">Lenovo</a></li>                                
                                <li><a href="../desktops/sony">Sony</a></li>
                                <li><a href="../desktops/toshiba">Toshiba</a></li>  
                            </ul>
                        </li>
                        <li><a href="../tablets">Tablets</a>
                            <ul>
                                <li><a href="../tablets/acer">Acer</a></li>
                                <li><a href="../tablets/amazon">Amazon Kindle</a></li>
                                <li><a href="../tablets/apple">Apple</a></li>
                                <li><a href="../tablets/archos">Archos</a></li>
                                <li><a href="../tablets/asus">Asus</a></li>
                                <li><a href="../tablets/atc">Atc</a></li>
                                <li><a href="../tablets/blackberry">Blackberry</a></li>
                                <li><a href="../tablets/dell">Dell</a></li>
                                <li><a href="../tablets/google">Google Nexus</a></li>
                                <li><a href="../tablets/hp">HP</a></li>
                                <li><a href="../tablets/htc">HTC</a></li>
                                <li><a href="../tablets/oem">OEM SYSTEMS</a></li>
                                <li><a href="../tablets/motorola">Motorola</a></li>
                                <li><a href="../tablets/samsung">Samsung</a></li>                                
                                <li><a href="../tablets/sony">Sony</a></li>
                                <li><a href="../tablets/toshiba">Toshiba</a></li>
                                <li><a href="../tablets/viewsonic">Viewsonic</a></li>  
                            </ul>
                        </li>
                        <li><a href="../hdd">External Hard Drives</a>
                            <ul>
                                <li><a href="../hdd/buffalo">Buffalo</a></li>
                                <li><a href="../hdd/hp">HP</a></li>
                                <li><a href="../hdd/iomega">Iomega</a></li>
                                <li><a href="../hdd/kingston">Kingston</a></li>
                                <li><a href="../hdd/lacie">LaCie</a></li>
                                <li><a href="../hdd/seagate">Seagate</a></li>
                                <li><a href="../hdd/synology">Synology</a></li>
                                <li><a href="../hdd/toshiba">Toshiba</a></li>
                                <li><a href="../hdd/transcend">Transcend</a></li>
                                <li><a href="../hdd/verbatim">Verbatim</a></li>
                                <li><a href="../hdd/westerndigital">Western Digital</a></li>
                            </ul>
                        </li>
                        <li><a href="../printers">Printers/Scanners</a>
                            <ul>
                                <li><a href="../printers/brother">Brother</a></li>
                                <li><a href="../printers/canon">Canon</a></li>
                                <li><a href="../printers/epson">Epson</a></li>                              
                                <li><a href="../printers/hp">HP</a></li>
                                <li><a href="../printers/kodak">Kodak</a></li>
                                <li><a href="../printers/lexmark">Lexmark</a></li>
                                <li><a href="../printers/okidata">Oki Data</a></li>
                                <li><a href="../printers/panasonic">Panasonic</a></li>
                                <li><a href="../printers/ricoh">Ricoh</a></li>
                                <li><a href="../printers/samsung">Samsung</a></li>
                            </ul>
                        </li>
                        <li><a href="../monitors">Monitors</a>
                            <ul>
                                <li><a href="../monitors/acer">Acer</a></li>
                                <li><a href="../monitors/apple">Apple</a></li> 
                                <li><a href="../monitors/asus">Asus</a></li>
                                <li><a href="../monitors/dell">Dell</a></li>
                                <li><a href="../monitors/gateway">Gateway</a></li>
                                <li><a href="../monitors/hp">HP</a></li>                  
                                <li><a href="../monitors/lenovo">Lenovo</a></li>
                                <li><a href="../monitors/panasonic">Panasonic</a></li>
                                <li><a href="../monitors/samsung">Samsung</a></li>
                                <li><a href="../monitors/sony">Sony</a></li>
                                <li><a href="../monitors/toshiba">Toshiba</a></li>
                                <li><a href="../monitors/viewsonic">Viewsonic</a></li>
                            </ul>
                        </li>
                        <li><a href="../routers">Routers</a>
                            <ul>
                                <li><a href="../routers/belkin">Belkin</a></li>
                                <li><a href="../routers/buffalo">Buffalo</a></li>
                                <li><a href="../routers/cisco">Cisco LinkSys</a></li>
                                <li><a href="../routers/dlink">D-Link</a></li>
                                <li><a href="../routers/lgericsson">LG-Ericsson</a></li>
                                <li><a href="../routers/motorola">Motorola</a></li>
                                <li><a href="../routers/netgear">Netgear</a></li> 
                                <li><a href="../routers/tplink">TP-Link</a></li>
                                <li><a href="../routers/trendnet">TrendNet</a></li>   
                                <li><a href="../routers/westerndigital">Western Digital</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Contact</a></li>          
                    </ul>
                </div>
            </div>
             <div id="left_nav">
                 <h3>Site Info</h3>
                 <ul>
                     <li><a href="../">Homepage</a></li>
                     <li><a href="../info/about">About</a></li>
                     <li><a href="../info/contact">Contact</a></li>
                 </ul>
                 
                 <h3>Guides</h3>
                 <ul>
                    <li><a href="../guides/laptops">Laptop Buying Guide</a></li>
                     <li><a href="../">Desktop Buying Guide</a></li>
                     <li><a href="../">Tablet Buying Guide</a></li>
                     <li><a href="../">Hard Drive Buying Guide</a></li>
                     <li><a href="../">Router Buying Guide</a></li>
                 </ul>
                 
                 <h3>Top Computers</h3>
                 <ul>
                        <li><a href="../laptops">Laptop Reviews</a>
                        <li><a href="../desktops">Desktop Reviews</a>
                        <li><a href="../tablets">Tablet Reviews</a>
                        <li><a href="../hdd">Hard Drive Reviews</a>
                        <li><a href="../printers">Printer/Scanner Reviews</a>
                        <li><a href="../monitors">Monitor Reviews</a>
                        <li><a href="../routers">Router Reviews</a>
                 </ul>
            </div>
            
            <div id="content">
                <?php if(isset($this->messages)): ?>
                    <div class="flashDiv">
                        <?php echo $this->messages[0]; ?>
                    </div>
                <?php endif; ?>
                
                <?php echo $this->layout()->content; ?>
            </div>
            
            <div id="footer">
                <br/>
                Copyright &copy 2012 Vishaan Tiwarie
                <br/>
                <br/>
                AllStuffComputers.com 
            </div>
        </div>
   
    </body>    
</html>