<h2>How To Choose a Laptop</h2>
<p><center><img class="guideImage" src="../images/laptopguidepic.jpg"/></center></p>
<p align="center">Last Updated: October 6th, 2012</p>

<br/>
<br/>
<div class="quickBrowseDiv"><a href="#Students">Students</a> | <a href="#Business">Business Travelers</a> | 
<a href="#Gamers">Gamers</a> | <a href="#Artists">Artists</a> | <a href="#Hobbyists">Hobbyists</a></div>
<br/>
<br/>



<h4 id="Students">Students</h4>

<br/>
<b>Portability</b>
<p>Students should look for a laptop that is light-weight and portable so that it
may be taken from class to class with ease.  A laptop between 7 and 14 inches works best for most
students.  Netbooks are a popular option for many students because they are low-cost, have great portability, are 
light-weight, and they can last for many hours before the battery dies.  This was incredibly useful for me
while I was in college.  No doubt, the <a href="../laptops/acer">Acer Aspire</a> laptops are simply the best way to go
because they offer a great deal of features for such a low price.</p>
<br/>
<b>Features</b>
<p>The typical functions of a laptop fit for students include browsing the web, emailing, writing papers, and other basic operations,
all of which do not require a top-performance PC.  In that case, you won't need a super powerful PC as would a 
gamer (unless of course you want to use it for gaming also).  You should make sure it comes with Microsoft Office,
or if it doesn't, you can just buy it yourself.</p>
<br/>
<b>Price</b>
<p>Students should expect to pay little more than $500 for a laptop because most of them in this price range
    will fit the requirements above.
</p>
<table border="3" width="60%" align="center" style="margin:20px auto">
    <tr><th colspan="2"><h4>Recommended for Students</h4></th></tr>
    <tr><td>Price Range</td><td>$300 - $500</td></tr>
    <tr><td>Weight</td><td>7 lbs. or less</td></tr>
    <tr><td>Processor</td><td>variable</td></tr>
    <tr><td>RAM</td><td>1 GB or higher</td></tr>
    <tr><td>Display</td><td>7" to 15"</td></tr>
    <tr><td>Graphics</td><td>ANY</td></tr>
    <tr><td>HDD space</td><td>150 GB or higher</td></tr>
    <tr><td>Additional Features</td><td>Microsoft Office Suite</td></tr>

</table>




<h4 id="Business">Business Travelers</h4>
<br/>
<b>Performance</b>
<p>The standard performance requirement for a traveling businessman can be somewhat
    variable, depending on the type of business to be performed.  If you are using high-end performance 
    software for your business, then of course, you will need a faster processor such as the Intel Core i7, lots
of RAM, and preferably good memory.  On the contrary, if you are going to be doing light web surfing
or emailing, then you can  settle for a lower performance dual core processor.</p>
<br/>
<b>Portability</b>
<p>This may be obvious, but a business traveler will most definitely require a portable laptop.
The laptop display should be no larger than 15 inches to ensure portability.  Laptops with
long battery life, say, at least 4.5 hours, will also be quite useful during travel where external
power is not supplied.  In considering the battery size, you don't want one that is too large, such as a 9 cell lithium ion,
because it doesn't allow for much portability (it sticks out the back of your computer), but if you choose
a smaller size, such as the 6 cell lithium ion, then your laptop will be more portable but its battery life won't be as lenghty.  This is
a trade-off that the businessman has to decide on.</p>
<br/>
<b>Features</b>
<p>For most businessmen, Microsoft Office is essential, so be sure to get one that comes with it
or you can buy it yourself.  Also, it's still quite unfortunate that most laptops today are still made of
plastic, even though Aluminum laptops are a much better alternative, given that they are durable, usually scratch resistant, 
and won't break as you carry it around.</p>
<br/>
<p>Having said all of this, the <a href="../laptops/lenovo">Lenovo Thinkpads</a> are a great option and are particularly built with
the businessman in mind.</p>
<br/>
<table border="3" width="60%" align="center" style="margin:20px auto">
    <tr><th colspan="2"><h4>Recommended for Business Travelers</h4></th></tr>
    <tr><td>Price Range</td><td>$500 or higher</td></tr>
    <tr><td>Weight</td><td>7 lbs. or less</td></tr>
    <tr><td>Processor</td><td>AMD E-Series, Intel Core 2 Duo/Quad, Intel Core i5, Intel Core i7</td></tr>
    <tr><td>RAM</td><td>4 GB - 8 GB</td></tr>
    <tr><td>Display</td><td>7" to 15"</td></tr>
    <tr><td>Graphics</td><td>variable</td></tr>
    <tr><td>HDD space</td><td>320 GB or higher</td></tr>
    <tr><td>Additional Features</td><td>Aluminum Material<br/>Microsoft Office Suite</br>Microsoft Windows 7 Professional<br/>DVD burner optical disk drive</td></tr>
</table>







<h4 id="Gamers">Gamers</h4>
<br/>

<b>Performance</b>
<p>Today's games require top-notch PC performance.  Serious gamers should look for cutting-edge processors, larger 
screen resolutions, advanced cooling systems, lots of RAM storage and preferably lots of hard drive space.  
The better the performance, the better your gaming experience will be.  Laptops such as <a href="../laptops/alienware">Alienware</a>
are ideal and very popular for gaming.  Be sure to get the latest processors, such as the Intel Core i7 or
Intel Core 2 Quad.  If you want to play games with high graphics, such as StarCraft 2, you will need an NVIDIA GeForce
graphics card or AMD Radeon HD at the least.  Also, high RAM is the least expensive way to improve your
PC performance so be sure to get at least 4 GB.</p> 
<br/>
<b>Maintenance</b>
<p>Since Gaming laptops are more costly, you won't be buying a new one too often.
    Instead, you're more likely to upgrade the parts that you already have, so be sure
    to pick one that is easy to upgrade.  You may also want to clean the fan with compressed air every month or so
in order to prevent dust buildup in the exhaust which causes your computer to get really hot and causes your computer
to crash when playing performance-demanding games.</p>
<table border="3" width="60%" align="center" style="margin:20px auto">
    <tr><th colspan="2"><h4>Recommended for Gamers</h4></th></tr>
    <tr><td>Price Range</td><td>$500 or higher</td></tr>
    <tr><td>Weight</td><td>variable</td></tr>
    <tr><td>Processor</td><td>Intel Core 2 Duo/Quad, Intel Core i5, Intel Core i7</td></tr>
    <tr><td>RAM</td><td>4 GB - 8 GB</td></tr>
    <tr><td>Display</td><td>15" or higher</td></tr>
    <tr><td>Graphics</td><td>NVIDIA GeForce or AMD Mobility Radeon HD</td></tr>
    <tr><td>HDD space</td><td>320 GB or higher</td></tr>
    <tr><td>Additional Features</td><td>Advanced Cooling<br/>Upgradeability</td></tr>
</table>




<h4 id="Artists">Artists</h4>
<br/>

<b>Performance</b>
<p>Like gamers, artists, such as CGI artists, DJ's, photographers, and videographers require  
    phenomenal performance.  They work with professional high resolution images and videos, and should therefore
look for higher screen resolutions for best results, preferably with full HD (1920 x 1080p).
The programs that are used in these arts, such as Adobe Photoshop and Pro Tools, require lots of memory, so 
be sure to get high RAM and hard drive storage.  Laptops such as 
<a target="_blank" href="http://www.amazon.com/HP-Envy-17-3270NR-17-3-Inch-Laptop/dp/B0085RV0AY%3FSubscriptionId%3DAKIAJ5MU3G2EY3HEKWPA%26tag%3Dvishaanamazon-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB0085RV0AY">HP Envy 17</a>
and <a target="_blank" href="http://www.amazon.com/Apple-MacBook-MD102LL-13-3-Inch-VERSION/dp/B007470SMM%3FSubscriptionId%3DAKIAJ5MU3G2EY3HEKWPA%26tag%3Dvishaanamazon-20%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB007470SMM">Macbook Pro</a>
are great fits and are amongst the most highly recommended PC's.  Not only do they have substantial performance, they also
have great battery life, extraordinary audio systems, high definition display, and massive storage space at 750 GB.</p>
<table border="3" width="60%" align="center" style="margin:20px auto">
    <tr><th colspan="2"><h4>Recommended for Artists</h4></th></tr>
    <tr><td>Price Range</td><td>$500 or higher</td></tr>
    <tr><td>Weight</td><td>variable</td></tr>
    <tr><td>Processor</td><td>Intel Core 2 Duo/Quad, Intel Core i5, Intel Core i7</td></tr>
    <tr><td>RAM</td><td>4 GB - 8 GB</td></tr>
    <tr><td>Display</td><td>15" or higher</td></tr>
    <tr><td>Graphics</td><td>NVIDIA GeForce or AMD Mobility Radeon HD</td></tr>
    <tr><td>HDD space</td><td>500 GB or higher</td></tr>
    <tr><td>Additional Features</td><td>Advanced Cooling<br/>Upgradeability<br/>DVD burner optical disk drive</td></tr>
</table>






<h4 id="Hobbyists">Hobbyists - Build Your Own PC</h4>
<br/>
<p>If you are an adventurer, you may consider building your own laptop.  This is a great
    alternative to buying from a computer manufacturer or reseller because you have complete
    control over everything that goes into your PC, and it will be easier to upgrade it with new parts in the
    future because you know exactly how your laptop is configured since you built it.  It also generally costs less
to build your own laptop, because you eliminate the entire profit margin of computer manufacturers that
you would otherwise have to pay.</p>
<br/>
<p>While this seems like a good idea, there is one downfall.  If your computer gets damaged, you 
    will not have tech support to guide you through the repair process, and also, there are no
    warranties on a computer you built on your own, so if your computer gets damaged, you will have to pay for all repairs regardless,
    and if it is totalled, say goodbye to it.</p>