<h2>About Vishaan</h2>

<p>My name is Vishaan Tiwarie and I am the founder of www.AllStuffComputers.com.  I recently graduated with a degree in
    Computer Engineering at the City College of New York.</p>
<br/>
<p>In college, I had a true love for computers and devices that can "think on its own".  I built computer systems from
    the ground up, both software and hardware.  One of my best projects include a Shakespeare concordancer, which is basically
    a computer program that reads in a line of input from the user and displays all of the lines and quotes associated with it.  
</p>
<br/>
<br/>
<p style="text-align:center"><img width="500px" height="600px" src="../images/concordancer.gif"/></p>
<p style="text-align:center"><b>Shakespeare Software Concordancer</b></p>
<br/>
<br/>
<br/>
<p>I've also done plenty of work in video games, web development, and embedded systems.
    One such project is the Raman Spectrometer, one of the most advanced systems I've ever created.
    This device detects any pill you can imagine, and lets you know if is real or fake!  So, I can
    present to you any aspirin pill, and you can verify with this device if indeed it is an aspirin
    pill, or if it is a counterfeit.  In addition, it is astonishingly accurate, with a 99.9% accuracy!!!</p>
<br/>
<p>This brings me to my next engineering endeavor: AllStuffComputers.com.  With this website, I intend
    to create the ultimate computers resource, equipped with computer buying guides, top ten reviews, user and expert reviews,
    video reviews, ratings, best-selling computers, and an online computer store.  It has everything YOU need to purchase your 
    next computer!




<br/>
<br/>
<br/>

